# navigation
[nav]
home = "文章"
archive = "归档"
about = "关于"

# about post
[post]
list = "所有文章"
archive = "归档"
tag = "标签"
readmore = "阅读更多"

# about pagination
[pager]
prev = "以前的"
next = "更新的"

[page]
index = "目录"